
DROP TABLE IF EXISTS member;

DROP TABLE IF EXISTS genre;

DROP TABLE IF EXISTS director;

DROP TABLE IF EXISTS content;

DROP TABLE IF EXISTS rating;

DROP TABLE IF EXISTS liked_content;

DROP TABLE IF EXISTS role;

DROP TABLE IF EXISTS session;
